heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameter_groups:
  - parameters:
      - floating-network-id
      - flavor
      - image
      - image-count
      - keyname

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small
  keyname:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
  floating-network-id:
    type: string
    label: Public network
    description: Network to attach instance to.
  image-count:
    type: number
    label: Instance count
    default: 3

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - network: { get_param: private_network }

outputs:
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }
